#
# JBZoo PHPUnit
#
# This file is part of the JBZoo CCK package.
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# @package    PHPUnit
# @license    MIT
# @copyright  Copyright (C) JBZoo.com, All rights reserved.
# @link       https://github.com/JBZoo/PHPUnit
#

phpqa:
  analyzedDirs:
    - ./src
    - ./bin
    - ./tests
  buildDir: build/phpqa
  ignoredDirs: vendor
  report: true
  execution: parallel
  output: file
  tools:
    - phpmetrics:1
    - phploc:1
    - phpcs:1
  #tools: phpmd,pdepend,phpcpd,phpstan,psalm,security-checker
  extensions:
    - php

phpcs:
  standard:
    - PSR12
  ignoreWarnings: false

phpmd:
  # alternatively you can use an array to define multiple rule sets (https://phpmd.org/documentation/index.html#using-multiple-rule-sets)
  standard: phpmd.xml

pdepend:
# coverageReport: build/coverage-clover.xml

phpcpd:
  minLines: 5
  minTokens: 70

phpmetrics:
  git: true
  # junit: build/log-junit.xml
  composer: composer.json

phpstan:
  level: max

psalm:
  config: psalm.xml
  deadCode: false
  threads: 1
  showInfo: true
