#
# JBZoo Toolbox - Codestyle
#
# This file is part of the JBZoo Toolbox project.
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# @package    Codestyle
# @license    MIT
# @copyright  Copyright (C) JBZoo.com, All rights reserved.
# @link       https://github.com/JBZoo/Codestyle
#

phpqa:
  analyzedDirs:
    - ./.phan
    - ./src
  buildDir: build/phpqa
  ignoredDirs: vendor
  report: true
  execution: parallel
  output: file
  tools:
    - phpmetrics:1
    - phploc:1
    - phpcs:1
    - php-cs-fixer:1
    - phpmd:1
    - pdepend:1
    - phpcpd:1
    - parallel-lint:1
    - phpstan:1
    - psalm:1
    - security-checker:1
  extensions:
    - php
    - phtml
  verbose: false

phpcs:
  standard:
    - ./src/phpcs/ruleset.xml
  reports:
    cli:
      - full
      - info
    file:
      info: phpcs-info.txt
      full: phpcs-full.txt


phpmd:
  standard: ./src/phpmd/jbzoo.xml


phpmetrics:
  git: true
  composer: ./composer.json


phpstan:
  level: max
  standard: ./phpstan.neon


psalm:
  config: ./psalm.xml
  deadCode: false
  threads: 1
  showInfo: true
