#
# JBZoo Toolbox - Codestyle
#
# This file is part of the JBZoo Toolbox project.
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# @package    Codestyle
# @license    MIT
# @copyright  Copyright (C) JBZoo.com, All rights reserved.
# @link       https://github.com/JBZoo/Codestyle
#

language: php
os: linux
dist: xenial

php:
  - 7.2
  - 7.3
  - 7.4

env:
  matrix:
    - JBZOO_COMPOSER_FLAGS="--prefer-lowest --prefer-stable"
    - JBZOO_COMPOSER_FLAGS=""

before_script:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - sudo apt update && sudo apt install graphviz

script:
  - make install               --no-print-directory
  - make codestyle             --no-print-directory
  - make test                  --no-print-directory
  - make test-composer-reqs    --no-print-directory
  - make report-phpqa          --no-print-directory
  - make report-composer-graph --no-print-directory
