#
# JBZoo Toolbox - Codestyle
#
# This file is part of the JBZoo Toolbox project.
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# @package    Codestyle
# @license    MIT
# @copyright  Copyright (C) JBZoo.com, All rights reserved.
# @link       https://github.com/JBZoo/Codestyle
#

language: php
os: linux
dist: xenial

php:
  - 7.2
  - 7.3
  - 7.4

before_script:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - sudo apt update && sudo apt install graphviz

script:
  - make install  --no-print-directory
  - make test-all --no-print-directory
