#
# JBZoo Toolbox - Codestyle
#
# This file is part of the JBZoo Toolbox project.
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# @package    Codestyle
# @license    MIT
# @copyright  Copyright (C) JBZoo.com, All rights reserved.
# @link       https://github.com/JBZoo/Codestyle
#

phpqa:
  analyzedDirs:
    - ./src
  buildDir: build/phpqa
  ignoredDirs: vendor
  report: true
  execution: parallel
  output: file
  verbose: false
  tools:
    - phpmetrics:1
    - phploc:1
    - phpcs:1
    #- php-cs-fixer:1
    - phpmd:1
    - pdepend:1
    - phpcpd:1
    - parallel-lint:1
    - phpstan:1
    - psalm:1
    - security-checker:1
  extensions:
    - php


phpcs:
  standard:
    - ../../../../../vendor/jbzoo/codestyle/src/phpcs/ruleset.xml
  reports:
    cli:
      - full
      - info
    file:
      info: phpcs-info.txt
      full: phpcs-full.txt


php-cs-fixer:
  rules: ../../../../../vendor/jbzoo/codestyle/src/phpcs/ruleset.xml
  isDryRun: true


phpmd:
  standard: ../../../../../vendor/jbzoo/codestyle/src/phpmd/jbzoo.xml


pdepend:
  #coverageReport: ../../../../../build/coverage_xml/main.xml


phpmetrics:
  git: true
  #junit: build/coverage_junit/main.xml
  composer: ../../../../../composer.json


phpstan:
  level: max
  standard: ../../../../../vendor/jbzoo/codestyle/phpstan.neon


psalm:
  config: ../../../../../vendor/jbzoo/codestyle/psalm.xml
  deadCode: false
  threads: 4
  showInfo: true
